sudo: false
language: scala
scala:
  - 2.12.6
jdk:
  - oraclejdk8
branches:
  only:
  - master
  - "/\\d+\\.\\d+\\.\\d+/"

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION dist
deploy:
  provider: releases
  api_key: ${GITHUB_KEY}
  file_glob: true
  file:
    - "target/universal/ot-genetics-api-latest.zip"
  on:
    repo: opentargets/genetics-api
    tags: true
  skip_cleanup: true
notifications:
  email:
    recipients:
    - mkarmona@gmail.com
    on_success: never
    on_failure: always
